[package]
name = "monkey_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.16.0"
monkey-derive = { path = "monkey_derive" }

[dev-dependencies]
table-test = "0.2.1"
